# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rheophysics of Soft Matter group
email: seto@ucas.ac.cn
address: No.1 Jinlian Road, Longwan District, Wenzhou, Zhejiang 325000, China
description: Our group studies soft matter physics. We study rheology and flow of soft materials by simulation and experiment.

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: ryseto


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryseto.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# https://scholar.google.co.jp/citations?user=0V-BankAAAAJ

# Build settings
# markdown: kramdown
# theme: minima

#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - github-pages
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#  - covid19.md
#   - Gemfile
#   - Gemfile.lock
#
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
